### PR TITLE
Add I18N support

### LINKED ISSUE #43: I18N
Currently, the page is based on a static webpage with hardcoded text in English. Instead, the elements should be added dynamically to the DOM, at which point we can replace the textual content by translated strings depending on the selection language.

### LINKED ISSUE #49: Missing translation
image

### PR DESCRIPTION
**Pull request by winniederidder**
This PR adds support for internationalization using [i18n-js](https://github.com/fnando/i18n-js).

dutch-papyros
This library was chosen due to ease of use and already being used in Dodona so this should help with the integration. Currently, English and Dutch translations are provided in src/Translations.ts.

In order to be able to translate the text, more control over the DOM was required. Instead of relying on an index.html file containing all the required elements, they are now created at run-time and filled in with the correct translation in the function renderPapyros. In order to provide this API, the Papyros.ts file was refactored to use a class-based approach, that now contains a static method fromElement to add it to an existing page. I tried reducing the scope pollution by combining related items into structured objects (such as the CodeState, InputState and StateManager) to hopefully aid in code readability and maintainability. This design will probably be fine-tuned later based on feedback and personal experience working with it.

Closes #43 
Closes #49 
Seems to have a positive impact on #44 , as the initial render is a lot less intense when reloading, so visual artefacts are reduced.
Perhaps this can be closed as well.

### CODE REVIEW

**Comment by pdawyndt** [comment]
`Programming language

**Comment by bmesuere** [comment]
Consider using the tiny [Polyglot.js](https://github.com/airbnb/polyglot.js) library which helps with nested keys and pluralization. In addition [i18n-extract](https://github.com/oliviertassinari/i18n-extract) can be used in the linting/testing flow to detect missing and unused translations.

**Comment by winniederidder** [comment]
> Consider using the tiny [Polyglot.js](https://github.com/airbnb/polyglot.js) library which helps with nested keys and pluralization.

Dodona uses I18n-js, which also supports these features and is still very small, no?

> In addition [i18n-extract](https://github.com/oliviertassinari/i18n-extract) can be used in the linting/testing flow to detect missing and unused translations.

I will look into this, thanks!

**Comment by bmesuere** [comment]
I thought I18n-js was specifically developed to bridge the gap and play nice with the rails i18n translation features. E.g., its translation file is automatically generated based the rails translations. I don't know if it's well suited for stand alone usage.

**Comment by winniederidder** [comment]
The PR description is now updated to be more descriptive @bmesuere .

**Review by bmesuere — APPROVED** [review]
👍

**Pull request merged**
